### ISSUE TITLE
Precomputed dimensionality reduction coordinates?

### ISSUE THREAD

**Issue by rargelaguet** [sajuukLyu/Guan_et_al._2022#1]
Hi Yulin,
congratulations on this cool work. I am trying to reproduce some visualisations from the article, but I can't get similar-looking embeddings. Would it be possible to upload the dimensionality reduction coordinates that you used for the paper (i.e. PCA, UMAP and force-atlas layout)?

Thanks,
Ricard

**Comment by sajuukLyu** [comment]
Thank you for your interest to our work. I have uploaded the cell annotation files of figure 2b and 3a, including cell dimensionality reduction coordinates of FA and UMAP, respectively.

**Comment by rargelaguet** [comment]
Thanks!
